version: 2

jobs:

  # using tox
  toxify:

      docker:
        - image: python:3.6
        - image: python:3.7

      steps:

        - checkout

        - run: pip install tox && tox

workflows:
  version: 2

  myproj:
    jobs:
      - toxify
